## QALI WARMA WEB SCRAPPING

This code allows web scrapping to the Qali-Warma/ consulta amigable page. The main purpose is to obtain information about the contracting of goods and services; from the data here you can obtain important reflections on budget management.

Author: Paola Aranda Flores

### 1.1 Installing the necessary libraries

In [2]:
import pandas as pd
import numpy as np
from selenium.webdriver.common.by import By
from io import StringIO
import os
import time
import requests
import re  # regex or regular expresion 
import time  ### time library

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select

from webdriver_manager.chrome import ChromeDriverManager

### 1.2. Setting the webdriver

In [3]:
url     = 'https://www.transparencia.gob.pe/enlaces/pte_transparencia_enlaces.aspx?id_entidad=14219 '
driver  = webdriver.Chrome()        
driver.get( url )
driver.maximize_window()

### 1.3. Extracting html code from the main buttons

In [4]:
contrataciones_button = driver.find_element( By.XPATH, '/html/body/section[2]/div/div/div/div/div/div/div[3]/div/ul/li[7]/a')
contrataciones_button .click()

In [6]:
ordenes_button = driver.find_element( By.XPATH, '/html/body/section[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[3]/p/a')
ordenes_button .click()

In [7]:
año_button = driver.find_element(By.XPATH, '/html/body/section[2]/div/div/div/div/div/div/form/table/tbody/tr[1]/td[2]/select/option[10]')
año_button .click()

In [8]:
mes_button = driver.find_element(By.XPATH, '/html/body/section[2]/div/div/div/div/div/div/form/table/tbody/tr[2]/td[2]/select/option[2]')
mes_button .click()

In [9]:
enviar_button = driver.find_element(By.XPATH, '/html/body/section[2]/div/div/div/div/div/div/form/table/tbody/tr[3]/td/input')
enviar_button .click()

### 1.4. Extracting the information in a table

In [28]:
#we prove the code with 2017
table_element = driver.find_element( By.XPATH, "//table[@class='table']" )
table_html    = table_element.get_attribute( 'outerHTML' )
table_html_io = StringIO( table_html )
table_df      = pd.read_html( table_html_io )[ 0 ]

In [29]:
table_df

,0,1,2,3,4,5,6,7
0,PERIODO DE LA ORDEN C/S,TIPO DE ORDEN,NUMERO DE LA ORDEN C/S,NUMERO DE SIAF,FECHA DE LA ORDEN C/S,MONTO (S/.),PROVEEDOR,DESCRIPCIÓN
1,17 de enero,Compra,1,275-4,17/01/2017,5280,SAVA ZAVALETA CARMEN LUISA,ADQUISICION DE DIARIOS DE REVISTAS PARA EL MON...
2,23 de enero,Compra,2,692-4,23/01/2017,15549.1,AG BUSINESS S.A.C,ADQUISICION DE BIDONES DE AGUA
3,10 de enero,Servicios,56,39-4,10/01/2017,9000,RUBIO AVILA LOURDES HAYDEE,SERVICIO DE ASISTENCIA TECNICA ADMINISTRATIVA
4,11 de enero,Servicios,64,41-4,11/01/2017,2500,VARGAS SOTO JOSE ANTONIO,SERVICIOS PARA TOMA DE INVENTARIO DE BIENES PA...
5,11 de enero,Servicios,63,42-4,11/01/2017,2500,ISMINIO ROMERO JOSELITO,SERVICIOS PARA TOMA DE INVENTARIO DE BIENES PA...
6,11 de enero,Servicios,62,43-4,11/01/2017,2500,PACHECO HURTADO SANDRO LORENZO,SERVICIOS PARA TOMA DE INVENTARIO DE BIENES PA...
7,11 de enero,Servicios,61,44-4,11/01/2017,2500,ROSSI CHACON JESUS ALEJANDRO,SERVICIOS PARA TOMA DE INVENTARIO DE BIENES PA...
8,11 de enero,Servicios,60,45-4,11/01/2017,2500,CALDERON PINO RICHAR LUIS,SERVICIOS PARA TOMA DE INVENTARIO DE BIENES PA...
9,11 de enero,Servicios,59,46-4,11/01/2017,2500,LA CHIRA VILLANUEVA PEDRO ALBERTO,SERVICIOS PARA TOMA DE INVENTARIO DE BIENES PA...
10,11 de enero,Servicios,58,47-4,11/01/2017,2500,PACHECO IPARRAGUIRRE SHIRLEY ANGELICA,SERVICIOS PARA TOMA DE INVENTARIO DE BIENES PA...
11,11 de enero,Servicios,57,48-4,11/01/2017,2500,ALMONACID INGA JIMMY WILLIAM,SERVICIOS PARA TOMA DE INVENTARIO DE BIENES PA...
12,6 de enero,Servicios,1,90-4,06/01/2017,18400,MIRANDA FLORES SERGIO EUGENIO,SERVICIO ESPECIALIZADO PARA ACTUALIZACION DE C...
13,11 de enero,Servicios,65,91-4,11/01/2017,2412.86,EMPRESA PERUANA DE SERVICIOS EDITORIALES S.A. ...,servicio de publicacion de resolucion director...
14,10 de enero,Servicios,50,92-4,10/01/2017,1178.12,NSF INASSA S.A.C.,SERVICIO DE SUPERVISION INICIAL A LAS PLANTAS ...
15,10 de enero,Servicios,51,93-4,10/01/2017,1625.56,NSF INASSA S.A.C.,SERVICIO DE SUPERVISION INICIAL A LAS PLANTAS ...
16,10 de enero,Servicios,53,94-4,10/01/2017,1744.52,NSF INASSA S.A.C.,SERVICIO DE SUPERVISION INICIAL A LAS PLANTAS ...
17,10 de enero,Servicios,52,95-4,10/01/2017,872.26,NSF INASSA S.A.C.,SERVICIO DE SUPERVISION INICIAL A LAS PLANTAS ...
18,10 de enero,Servicios,45,96-4,10/01/2017,2497.83,NSF INASSA S.A.C.,SERVICIO DE SUPERVISION INICIAL A LAS PLANTAS ...
19,10 de enero,Servicios,48,97-4,10/01/2017,1178.12,NSF INASSA S.A.C.,SERVICIO DE SUPERVISION INICIAL A LAS PLANTAS ...
20,10 de enero,Servicios,12,98-4,10/01/2017,5233.54,NSF INASSA S.A.C.,SERVICIO DE SUPERVISION INICIAL A LAS PLANTAS ...
21,10 de enero,Servicios,13,99-4,10/01/2017,7850.34,NSF INASSA S.A.C.,SERVICIO DE SUPERVISION INICIAL A LAS PLANTAS ...
22,10 de enero,Servicios,14,100-4,10/01/2017,3489.04,NSF INASSA S.A.C.,SERVICIO DE SUPERVISION INICIAL A LAS PLANTAS ...
23,10 de enero,Servicios,19,101-4,10/01/2017,8920.8,NSF INASSA S.A.C.,SERVICIO DE SUPERVISION INICIAL A LAS PLANTAS ...
24,10 de enero,Servicios,29,102-4,10/01/2017,2945.3,NSF INASSA S.A.C.,SERVICIO DE SUPERVISION INICIAL A LAS PLANTAS ...
25,10 de enero,Servicios,28,103-4,10/01/2017,2497.82,NSF INASSA S.A.C.,SERVICIO DE SUPERVISION INICIAL A LAS PLANTAS ...
26,10 de enero,Servicios,27,104-4,10/01/2017,8722.26,NSF INASSA S.A.C.,SERVICIO DE SUPERVISION INICIAL A LAS PLANTAS ...
27,10 de enero,Servicios,42,105-4,10/01/2017,892.08,NSF INASSA S.A.C.,SERVICIO DE SUPERVISION INICIAL A LAS PLANTAS ...
28,10 de enero,Servicios,44,106-4,10/01/2017,872.26,NSF INASSA S.A.C.,SERVICIO DE SUPERVISION INICIAL A LAS PLANTAS ...
29,10 de enero,Servicios,39,107-4,10/01/2017,14702.8,"BALTIC CONTROL, CALIDAD Y MEDIO AMBIENTE, LABO...",SERVICIO DE SUPERVISION INICIAL A LAS PLANTAS ...
30,10 de enero,Servicios,15,108-4,10/01/2017,18880,GENERAL CONTROL GROUP SOCIEDAD ANONIMA CERRADA,SERVICIO DE SUPERVISION INICIAL A LAS PLANTAS ...
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
headers_elements = driver.find_element( By.XPATH, '/html/body/section[2]/div/div/div/div/div/div/table[2]/tbody/tr[1]' ).find_elements( By.TAG_NAME, 'td' )
headers         = [ element.text for element in headers_elements  ]

print( headers, sep = '\n' )

['PERIODO DE LA ORDEN C/S', 'TIPO DE ORDEN', 'NUMERO DE LA ORDEN C/S', 'NUMERO DE SIAF', 'FECHA DE LA ORDEN C/S', 'MONTO (S/.)', 'PROVEEDOR', 'DESCRIPCIÓN']

In [31]:
#we establish the headers in each column
table_df.columns = headers
table_df = table_df.drop( table_df.columns[ 0 ], axis = 1 )
table_df.head( 5 )

,TIPO DE ORDEN,NUMERO DE LA ORDEN C/S,NUMERO DE SIAF,FECHA DE LA ORDEN C/S,MONTO (S/.),PROVEEDOR,DESCRIPCIÓN
0,TIPO DE ORDEN,NUMERO DE LA ORDEN C/S,NUMERO DE SIAF,FECHA DE LA ORDEN C/S,MONTO (S/.),PROVEEDOR,DESCRIPCIÓN
1,Compra,1,275-4,17/01/2017,5280,SAVA ZAVALETA CARMEN LUISA,ADQUISICION DE DIARIOS DE REVISTAS PARA EL MON...
2,Compra,2,692-4,23/01/2017,15549.1,AG BUSINESS S.A.C,ADQUISICION DE BIDONES DE AGUA
3,Servicios,56,39-4,10/01/2017,9000,RUBIO AVILA LOURDES HAYDEE,SERVICIO DE ASISTENCIA TECNICA ADMINISTRATIVA
4,Servicios,64,41-4,11/01/2017,2500,VARGAS SOTO JOSE ANTONIO,SERVICIOS PARA TOMA DE INVENTARIO DE BIENES PA...

In [32]:
table_df = table_df.drop(0).reset_index(drop=True)

In [33]:
table_df.reset_index(drop=True, inplace=True)
table_df.index += 1
table_df

,TIPO DE ORDEN,NUMERO DE LA ORDEN C/S,NUMERO DE SIAF,FECHA DE LA ORDEN C/S,MONTO (S/.),PROVEEDOR,DESCRIPCIÓN
1,Compra,1,275-4,17/01/2017,5280,SAVA ZAVALETA CARMEN LUISA,ADQUISICION DE DIARIOS DE REVISTAS PARA EL MON...
2,Compra,2,692-4,23/01/2017,15549.1,AG BUSINESS S.A.C,ADQUISICION DE BIDONES DE AGUA
3,Servicios,56,39-4,10/01/2017,9000,RUBIO AVILA LOURDES HAYDEE,SERVICIO DE ASISTENCIA TECNICA ADMINISTRATIVA
4,Servicios,64,41-4,11/01/2017,2500,VARGAS SOTO JOSE ANTONIO,SERVICIOS PARA TOMA DE INVENTARIO DE BIENES PA...
5,Servicios,63,42-4,11/01/2017,2500,ISMINIO ROMERO JOSELITO,SERVICIOS PARA TOMA DE INVENTARIO DE BIENES PA...
6,Servicios,62,43-4,11/01/2017,2500,PACHECO HURTADO SANDRO LORENZO,SERVICIOS PARA TOMA DE INVENTARIO DE BIENES PA...
7,Servicios,61,44-4,11/01/2017,2500,ROSSI CHACON JESUS ALEJANDRO,SERVICIOS PARA TOMA DE INVENTARIO DE BIENES PA...
8,Servicios,60,45-4,11/01/2017,2500,CALDERON PINO RICHAR LUIS,SERVICIOS PARA TOMA DE INVENTARIO DE BIENES PA...
9,Servicios,59,46-4,11/01/2017,2500,LA CHIRA VILLANUEVA PEDRO ALBERTO,SERVICIOS PARA TOMA DE INVENTARIO DE BIENES PA...
10,Servicios,58,47-4,11/01/2017,2500,PACHECO IPARRAGUIRRE SHIRLEY ANGELICA,SERVICIOS PARA TOMA DE INVENTARIO DE BIENES PA...
11,Servicios,57,48-4,11/01/2017,2500,ALMONACID INGA JIMMY WILLIAM,SERVICIOS PARA TOMA DE INVENTARIO DE BIENES PA...
12,Servicios,1,90-4,06/01/2017,18400,MIRANDA FLORES SERGIO EUGENIO,SERVICIO ESPECIALIZADO PARA ACTUALIZACION DE C...
13,Servicios,65,91-4,11/01/2017,2412.86,EMPRESA PERUANA DE SERVICIOS EDITORIALES S.A. ...,servicio de publicacion de resolucion director...
14,Servicios,50,92-4,10/01/2017,1178.12,NSF INASSA S.A.C.,SERVICIO DE SUPERVISION INICIAL A LAS PLANTAS ...
15,Servicios,51,93-4,10/01/2017,1625.56,NSF INASSA S.A.C.,SERVICIO DE SUPERVISION INICIAL A LAS PLANTAS ...
16,Servicios,53,94-4,10/01/2017,1744.52,NSF INASSA S.A.C.,SERVICIO DE SUPERVISION INICIAL A LAS PLANTAS ...
17,Servicios,52,95-4,10/01/2017,872.26,NSF INASSA S.A.C.,SERVICIO DE SUPERVISION INICIAL A LAS PLANTAS ...
18,Servicios,45,96-4,10/01/2017,2497.83,NSF INASSA S.A.C.,SERVICIO DE SUPERVISION INICIAL A LAS PLANTAS ...
19,Servicios,48,97-4,10/01/2017,1178.12,NSF INASSA S.A.C.,SERVICIO DE SUPERVISION INICIAL A LAS PLANTAS ...
20,Servicios,12,98-4,10/01/2017,5233.54,NSF INASSA S.A.C.,SERVICIO DE SUPERVISION INICIAL A LAS PLANTAS ...
21,Servicios,13,99-4,10/01/2017,7850.34,NSF INASSA S.A.C.,SERVICIO DE SUPERVISION INICIAL A LAS PLANTAS ...
22,Servicios,14,100-4,10/01/2017,3489.04,NSF INASSA S.A.C.,SERVICIO DE SUPERVISION INICIAL A LAS PLANTAS ...
23,Servicios,19,101-4,10/01/2017,8920.8,NSF INASSA S.A.C.,SERVICIO DE SUPERVISION INICIAL A LAS PLANTAS ...
24,Servicios,29,102-4,10/01/2017,2945.3,NSF INASSA S.A.C.,SERVICIO DE SUPERVISION INICIAL A LAS PLANTAS ...
25,Servicios,28,103-4,10/01/2017,2497.82,NSF INASSA S.A.C.,SERVICIO DE SUPERVISION INICIAL A LAS PLANTAS ...
26,Servicios,27,104-4,10/01/2017,8722.26,NSF INASSA S.A.C.,SERVICIO DE SUPERVISION INICIAL A LAS PLANTAS ...
27,Servicios,42,105-4,10/01/2017,892.08,NSF INASSA S.A.C.,SERVICIO DE SUPERVISION INICIAL A LAS PLANTAS ...
28,Servicios,44,106-4,10/01/2017,872.26,NSF INASSA S.A.C.,SERVICIO DE SUPERVISION INICIAL A LAS PLANTAS ...
29,Servicios,39,107-4,10/01/2017,14702.8,"BALTIC CONTROL, CALIDAD Y MEDIO AMBIENTE, LABO...",SERVICIO DE SUPERVISION INICIAL A LAS PLANTAS ...
30,Servicios,15,108-4,10/01/2017,18880,GENERAL CONTROL GROUP SOCIEDAD ANONIMA CERRADA,SERVICIO DE SUPERVISION INICIAL A LAS PLANTAS ...
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
# We establish the creation of a folder
path_qaliwarma_data    = './data'

os.makedirs( path_qaliwarma_data, exist_ok = True )

## Complete web scrapper code

In [40]:

driver = webdriver.Chrome() 
driver.maximize_window()
for k in range(2014,2016): #The years that exist on the page is since 2009
    driver.get("https://www.transparencia.gob.pe/enlaces/pte_transparencia_enlaces.aspx?id_entidad=14219")
    
    print(k)    
    
    # Selecting the Contrataciones se bienes y servicios button
    
    contrataciones_button = driver.find_element( By.XPATH, '/html/body/section[2]/div/div/div/div/div/div/div[3]/div/ul/li[7]/a')
    contrataciones_button .click()
    
    time.sleep(2)
    
    # Selecting the ordenes de servicio button
    
    ordenes_button = driver.find_element( By.XPATH, '/html/body/section[2]/div/div/div/div/div/div/table/tbody/tr[1]/td[3]/p/a')
    ordenes_button .click()

    time.sleep(1.5)
    
    # Choosing the year from the dropdown (loop by year)
  
    año_select = driver.find_element(By.XPATH, '/html/body/section[2]/div/div/div/div/div/div/form/table/tbody/tr[1]/td[2]/select')
    año_select.click()

    # Using the Select class to interact with the select element
    año_select_obj = Select(año_select)
    año_select_obj.select_by_value(str(k))
       
    time.sleep(2)

    lista_meses = list(range(2, 14))

    # Preparing loop to go for each month
    for i in lista_meses: 
        mes = driver.find_element(By.XPATH, "/html/body/section[2]/div/div/div/div/div/div/form/table/tbody/tr[2]/td[2]/select/option["+str(i)+"]").text # row i, columna 2
        print(mes) 
      
        driver.find_element(By.XPATH, "/html/body/section[2]/div/div/div/div/div/div/form/table/tbody/tr[2]/td[2]/select/option["+str(i)+"]").click()
              
        time.sleep(3)
        # enviar btton
        enviar_button = driver.find_element(By.XPATH, '/html/body/section[2]/div/div/div/div/div/div/form/table/tbody/tr[3]/td/input')
        enviar_button .click()
        #table element
        
        table_element = driver.find_elements(By.XPATH, "//table[@class='table']")

        # Checking if the table contains values, and if so proceed to download
        if table_element:
            table_html = table_element[0].get_attribute('outerHTML')
            table_html_io = StringIO(table_html)
            table_df = pd.read_html(table_html_io)[0]

        #making the first observation the name of the columns
        table_df .columns = table_df .iloc[0]
        table_df  = table_df[1:].reset_index(drop=True)
        # Downloading Excel files ###############################
        # Constructing the file path with the correct string formatting
        table_path = path_qaliwarma_data + f'/contrataciones_{k}_{i}.xlsx'

        table_df.to_excel(table_path, index=False)
       
        time.sleep(3)
    
        # Return to change month
        otro_mes= driver.find_element(By.XPATH, "/html/body/section[2]/div/div/div/div/div/div/form/table/tbody/tr[2]/td[2]/select/option["+str(i)+"]")
        otro_mes.click()
        
        time.sleep(3)

2014
Enero
Febrero
Marzo
Abril
Mayo
Junio
Julio
Agosto
Setiembre
Octubre
Noviembre
Diciembre
2015
Enero
Febrero
Marzo
Abril
Mayo
Junio
Julio
Agosto
Setiembre
Octubre
Noviembre
Diciembre